version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    container_name: keycloak
    ports:
      - 8043:8080
      - 8443:8443
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: 10.10.28.31:5432
      DB_DATABASE: keycloak_db
      DB_USER: postgres
      DB_SCHEMA: public
      DB_PASSWORD: postgres
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: 123456
      KEYCLOAK_FRONTEND_URL: https://localhost:8043/auth

  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      - LDAP_ORGANISATION="MyCompany Inc."
      - LDAP_DOMAIN=mycompany.com
    ports:
      - "389:389"

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
    ports:
      - "6443:443"
    depends_on:
      - openldap
